---

- block:
  - name: Create LDAP base directory
    file:
      path: "{{ openldap_directory }}"
      state: directory
      mode: 0755

  - name: Create LDAP data directory
    file:
      path: "{{ openldap_directory }}/data"
      state: directory
      mode: 0755

  - name: Create LDAP log directory
    file:
      path: "{{ openldap_directory }}/logs"
      state: directory
      mode: 0755

  - name: Create LDAP LDIFs directory
    file:
      path: "{{ openldap_directory }}/ldifs"
      state: directory
      mode: 0755

  - name: Create LDAP LDIFs directory
    file:
      path: "{{ openldap_directory }}/pkgs"
      state: directory
      mode: 0755
  tags: createopenldapdir

- name: Add external CentOS repo (in case LCC server is down)
  yum_repository:
    name: centos78-mirror
    description: CentOS 7 - Base
    baseurl: http://mirror.centos.org/centos/$releasever/os/$basearch/
    mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
    gpgcheck: no
  when: ansible_os_family == "RedHat" and openldap_repos == "centos78-mirror"
  
- name: Install OpenLDAP packages on RedHat
  yum:
    name: "{{ openldap_rpm_pkgs }}"
    state: present
    disablerepo: "*"
    enablerepo: "{{ openldap_repos }}"
  notify: restart slapd
  tags:
    - openldapinitialinstall
  when: ansible_os_family == "RedHat"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: schemas.yml
  when: ansible_os_family == "RedHat"

- include: overlays.yml
  when: ansible_os_family == "RedHat"

- include: users.yml
  when: ansible_os_family == "RedHat"
  tags: users
