---
# tasks file for ansible-role-openldap-lcc-cenapad
- name: get service facts
  service_facts:

- name: Configure firewalld
  firewalld: port={{ item }} permanent=true state=enabled immediate=true
  with_items:
    - 389/tcp
    - 636/tcp
  when:
    - ansible_facts.services["firewalld.service"] is defined
    - ansible_facts.services["firewalld.service"]["status"] == "enabled"
    - ansible_facts.services["slapd.service"]["status"] == "enabled"

- name: "Set the Open LDAP Server password"
  command: slappasswd -h {{ openldap_server_password_hash }} -s {{ openldap_server_rootpw }}
  register: rootpwgenerated
  tags:
    - changeopenldappasswd
    - openldapstep2

- debug:
    var: rootpwgenerated
