---
# default variables

openldap_directory: "/openldap"
openldap_server_directory: /var/lib/ldap
openldap_dir_certs: /etc/openldap/certs
openldap_repos:
  - centos78-lcc
  - rocks-centos7-os-lcc
  - rocks-centos7-os-lcc-updates
openldap_rpm_pkgs:
  - openldap
  - compat-openldap
  - openldap-clients
  - openldap-servers
  - openldap-servers-sql
  - unixODBC
  - cyrus-sasl-devel
  - openldap-devel
  - python-ldap
  - openssl
  - python2-cryptography
  - pyOpenSSL
#
openldap_domain: "dc=ufmg,dc=br"
server_domain: "lcc.ufmg.br"
slappasswd_args: -h "{SSHA}"
# slappasswd_args: -h "{SSHA512}" -o module-load=pw-sha2.la
#
openldap_manager: ldapadm
openldap_manager_password: veredas
#
# /etc/sysconfig/slapd:   defines the default ports 
# for LDAP, LDAPS (secured LDAP) and LDAPI
# (Interconnect = Unix Sockect)
openldap_slapd_file: /etc/sysconfig/slapd
openldap_default_services: ldapi:/// ldap://127.0.0.1 ldaps:///
openldap_default_options: ""
# size of 2MB
openldap_dbconfig_set_cachesize: 2097152
openldap_schemas:
  - cosine
  - nis
  - inetorgperson
  - eduperson
  - breduperson
  - schac-20061212-1
  - samba

# Overlay attributes
openldap_overlays:
  - name: smbk5pwd
    objectClass:
      - olcOverlayConfig
      - olcSmbK5PwdConfig
      - olcConfig
      - top
    attributes:
      olcOverlay: smbk5pwd
      olcSmbK5PwdEnable: samba
  - name: memberof
    objectClass:
      - olcOverlayConfig
      - olcMemberOf
      - olcConfig
      - top
    attributes:
      olcOverlay: memberof
      olcMemberOfDangling: ignore
      olcMemberOfRefInt: 'TRUE'
      olcMemberOfGroupOC: groupOfNames
      olcMemberOfMemberAD: member
      olcMemberOfMemberOfAD: memberOf
  - name: refint
    objectClass:
      - olcOverlayConfig
      - olcRefintConfig
      - olcConfig
      - top
    attributes:
      olcOverlay: refint
      olcRefintAttribute: 
        - memberof
        - member
        - manager
        - owner
#
# groups and special users
#
ldap_groups_users_list:
  - groupname: admins
    acl: "by group.base=\"cn=admin, ou=groups, {{ openldap_domain }}\" write"
    users:
      - username: admin
        password: "veredas1"
        gecos: "Administrador da base LDAP"
        acl: "by dn.base=\"cn=admin, {{ openldap_domain }}\" write"
  - groupname: leitores
    acl: "by group.base=\"cn=leitores, ou=groups, {{ openldap_domain }}\" read"
    users:
      - username: leitor-shib
        password: "veredas3"
        gecos: "Leitor da base para o Shibboleth"
        acl: "by dn.base=\"cn=leitor-shib, {{ openldap_domain }}\" read"
